"""empty message

Revision ID: 159214abd804
Revises: 
Create Date: 2023-03-01 20:09:31.232551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159214abd804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invRoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invStatusUsuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invEmpleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('Puesto', sa.String(length=100), nullable=True),
    sa.Column('salario', sa.Integer(), nullable=True),
    sa.Column('statusId', sa.Integer(), nullable=False),
    sa.Column('fechaAlta', sa.Date(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.Column('fechaContratacion', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=100), nullable=True),
    sa.Column('rolId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rolId'], ['invRoles.id'], ),
    sa.ForeignKeyConstraint(['statusId'], ['invStatusUsuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invBeneficiarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('parentezco', sa.String(length=100), nullable=True),
    sa.Column('statusId', sa.Integer(), nullable=False),
    sa.Column('empleadoId', sa.Integer(), nullable=False),
    sa.Column('fechaAlta', sa.Date(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['empleadoId'], ['invEmpleados.id'], ),
    sa.ForeignKeyConstraint(['statusId'], ['invStatusUsuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invBeneficiarios')
    op.drop_table('invEmpleados')
    op.drop_table('invStatusUsuarios')
    op.drop_table('invRoles')
    # ### end Alembic commands ###
